<?php

namespace PliageBundle\Repository;

/**
 * PliageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PliageRepository extends \Doctrine\ORM\EntityRepository
{
}
