pliage_homepage:
    path:     /
    defaults: { _controller: PliageBundle:Default:index }
    
pliage_accueil:
    path:     /home
    defaults: { _controller: PliageBundle:Default:accueil }
    
pliage_contact:
    path:     /contact
    defaults: { _controller: PliageBundle:Contact:index }
    
pliage_creationcontact:
    path:     /creationcontact
    defaults: { _controller: PliageBundle:Contact:add }    
    
pliage_debitpliage:
    path:     /debitpliage
    defaults: { _controller: PliageBundle:Pliage:debit }
    